name: cheetah
description: A micro-framework like Express.js or Koa.js for Dart backend development.
version: 0.0.1
repository: https://github.com/gustavovalle23/cheetah

environment:
  sdk: ^3.5.2

dependencies:
  collection: ^1.19.0
  mongo_dart: ^0.10.4
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  mockito: ^5.4.4
